name: flatland-env
dependencies:
    - python=3.7
    - pip=20.0
    - pip:
        - git+https://gitlab.aicrowd.com/flatland/flatland.git@master
        - CairoSVG==2.4.2
#       - pycairo==1.19.1 # fails!
        - pyhumps==1.3.1
        - gputil==1.4.0
        - pyhumps==1.3.1
        - wandb==0.8.36
        - ray[rllib]==0.8.5
        - tensorflow==2.1.0